{
  "comments": [
    {
      "key": {
        "uuid": "ac13780b_4e09791b",
        "filename": "lftools/shell/__init__.py",
        "patchSetId": 7
      },
      "lineNbr": 0,
      "author": {
        "id": 192
      },
      "writtenOn": "2019-10-17T22:41:23Z",
      "side": 1,
      "message": "Do we need copyright/license information in an empty file? Seems a little unnecessary, since there\u0027s no code to be copyrighted/licensed.",
      "revId": "52c98016039a5328bbeeb3bea41dc8dc6cc1ddb1",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "b4ef2e03_393fee14",
        "filename": "lftools/shell/dco.py",
        "patchSetId": 7
      },
      "lineNbr": 26,
      "author": {
        "id": 192
      },
      "writtenOn": "2019-10-17T22:41:23Z",
      "side": 1,
      "message": "Shouldn\u0027t this just be an \"else\"? I know the end result is the same, but it seems weird to me to do if/if not rather than if/else.",
      "range": {
        "startLine": 26,
        "startChar": 4,
        "endLine": 26,
        "endChar": 18
      },
      "revId": "52c98016039a5328bbeeb3bea41dc8dc6cc1ddb1",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "46a85274_cbad0fe0",
        "filename": "lftools/shell/dco.py",
        "patchSetId": 7
      },
      "lineNbr": 37,
      "author": {
        "id": 192
      },
      "writtenOn": "2019-10-17T22:41:23Z",
      "side": 1,
      "message": "Should hashes be declared outside the loop, and then appended here? As it is, this could run several times in the loop, and would only return the last value found.",
      "range": {
        "startLine": 37,
        "startChar": 12,
        "endLine": 37,
        "endChar": 45
      },
      "revId": "52c98016039a5328bbeeb3bea41dc8dc6cc1ddb1",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "75580c6c_b35b84e4",
        "filename": "lftools/shell/dco.py",
        "patchSetId": 7
      },
      "lineNbr": 47,
      "author": {
        "id": 192
      },
      "writtenOn": "2019-10-17T22:41:23Z",
      "side": 1,
      "message": "Since this exception is effectively the end of the method, should it exit or return a value?",
      "range": {
        "startLine": 45,
        "startChar": 4,
        "endLine": 47,
        "endChar": 0
      },
      "revId": "52c98016039a5328bbeeb3bea41dc8dc6cc1ddb1",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "93df1fab_b596a597",
        "filename": "lftools/shell/dco.py",
        "patchSetId": 7
      },
      "lineNbr": 63,
      "author": {
        "id": 192
      },
      "writtenOn": "2019-10-17T22:41:23Z",
      "side": 1,
      "message": "Same issue as exception above.",
      "range": {
        "startLine": 62,
        "startChar": 4,
        "endLine": 63,
        "endChar": 20
      },
      "revId": "52c98016039a5328bbeeb3bea41dc8dc6cc1ddb1",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "87eb2500_ebc3dffb",
        "filename": "lftools/shell/dco.py",
        "patchSetId": 7
      },
      "lineNbr": 83,
      "author": {
        "id": 192
      },
      "writtenOn": "2019-10-17T22:41:23Z",
      "side": 1,
      "message": "This only seems to be checking if there is a Signed-off-by line. There is no check here to see if it matches the Author.",
      "range": {
        "startLine": 78,
        "startChar": 20,
        "endLine": 83,
        "endChar": 63
      },
      "revId": "52c98016039a5328bbeeb3bea41dc8dc6cc1ddb1",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "c34441ad_3f554bb7",
        "filename": "lftools/shell/dco.py",
        "patchSetId": 7
      },
      "lineNbr": 92,
      "author": {
        "id": 192
      },
      "writtenOn": "2019-10-17T22:41:23Z",
      "side": 1,
      "message": "Same issue as exception above.",
      "range": {
        "startLine": 91,
        "startChar": 4,
        "endLine": 92,
        "endChar": 20
      },
      "revId": "52c98016039a5328bbeeb3bea41dc8dc6cc1ddb1",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": true
    }
  ]
}